#pragma once


#define CHEVALIER_WINDOW_HEIGHT_DEFAULT 480
#define CHEVALIER_WINDOW_WIDTH_DEFAULT 720


#define CHEVALIER_ENABLE_VALIDATION_LAYERS false

#define CHEVALIER_MAX_FRAMES_IN_FLIGHT 2

#define CHEVALIER_CONSTANTS_INITIAL_MODEL_COUNT 100

#define CHEVALIER_CONSTANTS_MAX_POINT_LIGHTS 10
#define CHEVALIER_CONSTANTS_MAX_SPOT_LIGHTS 10
#define CHEVALIER_CONSTANTS_MAX_DIRECTIONAL_LIGHTS 1

#define CHEVALIER_CONSTANTS_INITIAL_LIGHTING_COUNT 10

